### ISSUE TITLE
acme_cape parameters propagation issue 

### ISSUE THREAD

**Issue by Jerome-Neanne** [ARM-software/workload-automation#1036]
This issue is related with fix proposal for: https://github.com/ARM-software/workload-automation/issues/1035

Changing to latest devlib version is showing some kind of regression when using acme_cape instrument (this issue is not visible with devlib 1.1.2)

acme_cape parameters: host and iio_devices are always loaded with default values regardless of agenda values, here in my case:
config:
  instrumentation: [dmesg, cpufreq, energy_measurement]
  energy_measurement:
    instrument: acme_cape
  acme_cape:
    host: baylibre-acme-ptec-jn.local
    iio_devices: iio:device3

The parsing looks correct since we can see the correct name in the log (caching...)
[run_acme_param.log](https://github.com/ARM-software/workload-automation/files/3859325/run_acme_param.log)

But later on the host value is not used and default parameter is used instead.

The funny thing is it can be hacked by changing default value in energy_measurement.py (wa side not devlib)

So the parameter is somehow transmitted to devlib. 

Parsing is correct on wa side but parameter is "lost" before reaching energy_measurement.py. Looks like it is lost only if using latest devlib version (no idea why). 
Don't have same issue with other parameter like:
 energy_measurement:
    instrument: acme_cape

While structure looks very symetric.

**Comment by marcbonnici** [comment]
I'm not sure quite sure your config looks quite correct although if you haven't changed it I'm unsure how it was working initially. 

In order to provide configuration to the energy instrument you should be passing it in via `instrument_parameters` to the `energy_measurement` instrument. 
https://workload-automation.readthedocs.io/en/latest/plugins/instruments.html#energy-measurement 

The structure can also be generated with the create command e.g. 
`wa create agenda dmesg cpufreq energy_measurement acme_cape`
which will look something like: 
```
config:
    instrumentation: [dmesg, cpufreq, energy_measurement]
    energy_measurement:
    instrument: acme_cape
    instrument_parameters:
        host: baylibre-acme-ptec-jn.local
        iio_devices: iio:device3
```


(Also as a side note I notice you are still running the official release of WA with a development version of devlib, as a general rule it's a good idea to synchronise update to packages to minimise conflicts.)

**Comment by Jerome-Neanne** [comment]
This synthax does not even pass parser with the WA version I'm using:
```
(WAvenv) nxf44606@nxf41552-l-11:~/Baylibre/TPMPstandard/WorkloadAuto/workload-automation$ wa run -c NXP845.yaml ./acmeagenda.yaml -f
INFO     Removing existing output directory.
INFO     Creating output directory.
ERROR    Error in "./acmeagenda.yaml":
ERROR    	Error in "./acmeagenda.yaml/config":
ERROR    configuration provided for unknown plugin "instrument_parameters"
(WAvenv) nxf44606@nxf41552-l-11:~/Baylibre/TPMPstandard/WorkloadAuto/workload-automation$ 
```
I'll try dev version of WA with dev version of devlib as you suggested as it really looks like a misalignment (config format change creating a discrepancy between both sides)

**Comment by marcbonnici** [comment]
Sorry it looks like the indentation got lost slightly in my previous example it should have been:
```
config:
    instrumentation: [dmesg, cpufreq, energy_measurement]
    energy_measurement:
        instrument: acme_cape
        instrument_parameters:
            host: baylibre-acme-ptec-jn.local
            iio_devices: iio:device3
```
