### ISSUE TITLE
Runtime parameter cpufreq change failure on Pixel 6 (root access, Android 13)

### ISSUE THREAD

**Issue by hosunys** [ARM-software/workload-automation#1200]
I've been trying to control the cpu frequency before each run without much success. I've mostly been using this [CPUFreq](https://workload-automation.readthedocs.io/en/latest/user_information.html?highlight=cpufreq#cpufreq) explanation to set the frequencies for my agenda.
For the basic config I have enabled cpufreq like so
```
config:
   device_config:
      modules: ['cpufreq']
```
And I've tried the many different methods:
```
sections:
-   id: all_max
    runtime_parameters: 
        cpu0_frequency: 1803000
        cpu1_frequency: 1803000
        cpu2_frequency: 1803000
        cpu3_frequency: 1803000
        cpu4_frequency: 2253000
        cpu5_frequency: 2253000
        cpu6_frequency: 2802000
        cpu7_frequency: 2802000
```
The method above says gets an error says `ERROR    Cannot set "frequency" for core "1"; Parameter for CPU0 has already been set`

Next I tried `<core_name>_frequency: 180300` where core_names were `a55`, `A55`, and `policy0`, which have all failed saying `Unknown runtime parameter: a55_frequency`.

I also tried:
```
sections:
-   id: all_max
    runtime_parameters: 
        sysfile_values:
            /sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq: 300000
            /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq: 300000
            /sys/devices/system/cpu/cpufreq/policy4/scaling_min_freq: 400000
            /sys/devices/system/cpu/cpufreq/policy4/scaling_max_freq: 400000
            /sys/devices/system/cpu/cpufreq/policy6/scaling_min_freq: 500000
            /sys/devices/system/cpu/cpufreq/policy6/scaling_max_freq: 500000
```
Except the error message seems to imply that it successfully changed policy0 and 4, but failing at 6. 
```
ERROR        Could not write "500000" to /sys/devices/system/cpu/cpufreq/policy6/scaling_max_freq: 
INFO         Completing job all_max-wk1
ERROR    Job all_max-wk1 iteration 1 completed with status FAILED. retrying...
INFO     Running job all_max-wk1
INFO         Configuring augmentations
INFO         Configuring target for job all_max-wk1 (dhrystone) [1]
ERROR        Could not write "500000" to /sys/devices/system/cpu/cpufreq/policy6/scaling_max_freq: 
INFO         Completing job all_max-wk1
ERROR    Job all_max-wk1 iteration 1 completed with status FAILED. Max retries exceeded.
```

Finally, I tried:
```
sections:
-   id: all_max
    runtime_parameters: 
        sysfile_values:
            # A55
            /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq: 1803000
            /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: 1803000
            /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq: 1803000
            /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq: 1803000
            /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq: 1803000
            /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq: 1803000
            /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq: 1803000
            /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq: 1803000
            # A76
            /sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq: 2253000
            /sys/devices/system/cpu/cpu4/cpufreq/scaling_max_freq: 2253000
            /sys/devices/system/cpu/cpu5/cpufreq/scaling_min_freq: 2253000
            /sys/devices/system/cpu/cpu5/cpufreq/scaling_max_freq: 2253000
            # X1
            /sys/devices/system/cpu/cpu6/cpufreq/scaling_min_freq: 2802000
            /sys/devices/system/cpu/cpu6/cpufreq/scaling_max_freq: 2802000
            /sys/devices/system/cpu/cpu7/cpufreq/scaling_min_freq: 2802000
            /sys/devices/system/cpu/cpu7/cpufreq/scaling_max_freq: 2802000
```
Also getting an error message:
```
INFO         Configuring target for job all_max-wk1 (dhrystone) [1]
ERROR        Could not set the value of /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq to "1803000" (read "300000
ERROR        ")
INFO         Completing job all_max-wk1
ERROR    Job all_max-wk1 iteration 1 completed with status FAILED. retrying...
INFO     Running job all_max-wk1
INFO         Configuring augmentations
INFO         Configuring target for job all_max-wk1 (dhrystone) [1]
ERROR        Could not set the value of /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq to "1803000" (read "300000
ERROR        ")
INFO         Completing job all_max-wk1
ERROR    Job all_max-wk1 iteration 1 completed with status FAILED. retrying...
INFO     Running job all_max-wk1
INFO         Configuring augmentations
INFO         Configuring target for job all_max-wk1 (dhrystone) [1]
ERROR        Could not set the value of /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq to "1803000" (read "300000
ERROR        ")
INFO         Completing job all_max-wk1
ERROR    Job all_max-wk1 iteration 1 completed with status FAILED. Max retries exceeded.
```
I guess I just want to know how I can fix this issue, or would I have to change the values myself through adb shell outside of wa? Also the Pixel 6 doesn't have userspace governor, but the documentation says that it'll automatically attempt max/min so these are all that I've tried.

**Comment by marcbonnici** [comment]
>  how I can fix this issue, or would I have to change the values myself through adb shell outside of wa?

This is absolutely something that WA should be able to handle. I have a few thoughts.

> Finally, I tried: (sysfile_values)
`ERROR        Could not set the value of /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq to "1803000" (read "300000`

One thing to note when setting the sysfiles is that WA will try to set them in the exact order they are listed in the agenda as these are order specific. For example if the current values of `min_freq` and `max_freq` at set to `300000`, and the first instruction is to set the minimum frequency to `1803000`, this is larger than `max_freq` and the device will reject/ignore the request as it is invalid and I suspect could be the cause of your errors. This is something that using the runtime parameters methods should handle automatically.


> Next I tried <core_name>_frequency: 180300 where core_names were a55, A55, and policy0, which have all failed saying Unknown runtime parameter: a55_frequency

This will happen if devlib/WA cannot automatically detect the core names (these are the ones that devlib currently knows about [1]). However, these can be specified manually so you could add something like the following line into your agenda.
```
device_config:
    core_names: ['A55', 'A55', 'A55', 'A55', 'A76', 'A76', 'X1', 'X1']
```

This should then allow you to use the format:
```
sections:
-   id: all_max
    runtime_parameters: 
        a55_frequency: 1803000
        a76_frequency: 1803000
        x1_frequency: 1803000
```

Finally, for your original attempt
```
sections:
-   id: all_max
    runtime_parameters: 
        cpu0_frequency: 1803000
        cpu1_frequency: 1803000
        cpu2_frequency: 1803000
        cpu3_frequency: 1803000
        cpu4_frequency: 2253000
        cpu5_frequency: 2253000
        cpu6_frequency: 2802000
        cpu7_frequency: 2802000
```
As part of setting the cpu frequencies WA will detect other cpus that are affected by a given parameter to prevent any conflicts. In this case the values are the same, so thinking about it it might make more sense to not to thrown an error here, however in this instance I suspect the error is being thrown because WA is receiving values for multiple (all) cpus that overlap with other cpus on the same frequency domain.
Could you try modifying this to only include unique domains? For example something like:
```
sections:
-   id: all_max
    runtime_parameters: 
        cpu0_frequency: 1803000
        cpu4_frequency: 2253000
        cpu6_frequency: 2802000
```

Please let me know if any of above helps and if so, we can look into trying to make this a bit more user friendly to understand. 

[1] https://github.com/ARM-software/devlib/blob/111aa327ce0e9555a5905bd16831a157a0e0cdf5/devlib/utils/misc.py#L65
