### ISSUE TITLE
Issues with some workloads

### ISSUE THREAD

**Issue by vickariofillis** [ARM-software/workload-automation#1215]
**
I have some issues with using WA with a Qualcomm development board.

1. I tried running Geekbench 5 but I got errors about no internet connection even though the development is connected to the internet via WiFi.
2. After installing Geekbench 6 as well, there is an error about multiple matches (5 & 6). Is it possible to specify the version with a command line argument? If not, do I have to specify it in the yaml config file (and if yes, where is it located)?
3.  I tried copying some of the YAML file examples from the User Guide but I keep getting the same error.

`ERROR    Error in "configs/test.yaml":`
`ERROR    "config" entry specified inside config/global section; If this is defined in a config file, move the entry content into the top level`

Thank you.

**Comment by marcbonnici** [comment]
1. The internet connectivity check is performed by attempting to ping google's DNS servers from the device and detecting if this operation is successful or not. [1] Could you confirm whether this operation succeeds from your device?
2. This is specified in the agenda (yaml config file) as WA has detected both version on your device and is unsure which you want to run. You can specify this via the `version` parameter so you can set this to either `5` or `6` and WA should run the correct version (The full list of allowed versions can be found here [2]).
3. If you're having trouble generating the the agenda you can use the built in `create` command to generate one for reference. E.g.
`wa create agenda geekbench -o my_geekbench_agenda.yaml`
This can then be customized so an agenda to run version 6 should look something like:
```
config:
    augmentations: []
    iterations: 1
workloads:
-   name: geekbench
    params:
        loops: 1
        prefer_host_package: true
        strict: false
        timeout: 3600
        uninstall: false
        variant: null
        version: 6
        ...
```

Also 2ould you be able to point me to the documentation this causing this confusion and I can see if this can be clarified?


[1] https://github.com/ARM-software/devlib/blob/be988bb42b766574bb9bd9191fa3532a65091716/devlib/target.py#LL1499C1-L1499C1  
[2] https://github.com/ARM-software/devlib/blob/be988bb42b766574bb9bd9191fa3532a65091716/devlib/target.py#LL1499C1-L1499C1
