### ISSUE TITLE
Regarding Runtime Parameter

### ISSUE THREAD

**Issue by hosunhc** [ARM-software/workload-automation#1217]
The device that I am using has three clusters as shown in the  device_config below:
```
  device_config:
    adb_server:
    big_core:
    core_clusters:
    core_names: ['A55', 'A55', 'A55', 'A55', 'A76', 'A76', 'X1', 'X1']
```
And if I try to change the frequency of cluster A76 when CPU4 is off, WA returns an error saying that it is not possible due to CPU4 being off even though CPU5, a cpu in the same cluster, is on:

```
  runtime_parameters:
    A55_frequency: 1328000
    A76_frequency: 1328000
    X1_frequency: 1745000
    sysfile_values:
      /sys/devices/system/cpu/cpu1/online: 0
      /sys/devices/system/cpu/cpu2/online: 1
      /sys/devices/system/cpu/cpu3/online: 0
      /sys/devices/system/cpu/cpu4/online: 0
      /sys/devices/system/cpu/cpu5/online: 1
      /sys/devices/system/cpu/cpu6/online: 1
      /sys/devices/system/cpu/cpu7/online: 0
```
Is there no way around this? Is it because CPU5 frequency is fixed to CPU4? Any advice is appreciated. The device is Pixel 6.

**Comment by marcbonnici** [comment]
Hi, thanks for reporting this, that should not be the case so sounds like we might have a bug somewhere.

As a workaround could you try explicitly specifying the frequency of the enabled cores that you are looking for and see if that allows you to make progress?

e.g.
```
cpu2_frequency: 1328000
cpu5_frequency: 1328000
cpu6_frequency: 1745000
```

**Comment by hosunhc** [comment]
Thanks for the quick response. Still does not seem to work:
```

workloads:
- name: stress-ng
  iterations: 10
  params:
    cleanup_assets: true
    duration: 10
    extra_args: '--cpu-method callfunc --taskset 6,7 -l 100'
    stressor: cpu
    threads: 2
    uninstall: false
  runtime_parameters:
    # A55_frequency: 1328000
    # A76_frequency: 1328000
    # X1_frequency: 1745000
    cpu2_frequency: 1328000
    cpu5_frequency: 1328000
    cpu6_frequency: 1745000
    sysfile_values:
      /sys/devices/system/cpu/cpu1/online: 0
      /sys/devices/system/cpu/cpu2/online: 1
      /sys/devices/system/cpu/cpu3/online: 0
      /sys/devices/system/cpu/cpu4/online: 0
      /sys/devices/system/cpu/cpu5/online: 1
      /sys/devices/system/cpu/cpu6/online: 1
      /sys/devices/system/cpu/cpu7/online: 1
```
With the output as below:
```
INFO     Running job wk1
INFO         Configuring augmentations
INFO         Configuring target for job wk1 (stress-ng) [1]
ERROR        Cannot configure frequencies for CPU4 as no CPUs are online.
INFO         Completing job wk1
ERROR    Job wk1 iteration 1 completed with status FAILED. retrying...
INFO     Running job wk1
INFO         Configuring augmentations
INFO         Configuring target for job wk1 (stress-ng) [1]
ERROR        Cannot configure frequencies for CPU4 as no CPUs are online.
INFO         Completing job wk1
ERROR    Job wk1 iteration 1 completed with status FAILED. retrying...
INFO     Running job wk1
INFO         Configuring augmentations
INFO         Configuring target for job wk1 (stress-ng) [1]
ERROR        Cannot configure frequencies for CPU4 as no CPUs are online.
INFO         Completing job wk1
ERROR    Job wk1 iteration 1 completed with status FAILED. Max retries exceeded.
```

**Comment by hosunhc** [comment]
Ahhhh i see, I was hoping that that wasnt the case as I would prefer having the flexibility of particular cpus

**Comment by marcbonnici** [comment]
I think I've found the problem (and a few others in the process). Would you be able to try out this [1] branch on your setup and let me know if this resolves the issue for you? 


[1] https://github.com/marcbonnici/workload-automation/tree/cpu_domain_fix

**Comment by hosunhc** [comment]
Okay, so I switched branches, and i just used the setup.py and followed the installation with:
```
cd workload-automation
sudo -H python setup.py install
```
And the given version is 3.4.0.dev1+7c432d74. but the issue still seems to occur.

**Comment by marcbonnici** [comment]
Hmm.. thanks for trying that out. 
Do you have your `run.log` available to see if there are any further hints in there?

**Comment by marcbonnici** [comment]
Thanks, would you be able to pull my branch again and see if this resolves this problem for you?

**Comment by hosunhc** [comment]
Still seems to be happening.
[run.log](https://github.com/ARM-software/workload-automation/files/11923887/run.log)

**Comment by scojac01** [comment]
Hi Honsunhc - what happens if you try to explicitly set the frequency for each CPU, rather than the cluster frequency? 

e.g
```
  runtime_parameters:
    cpu0_frequency: 1328000
    cpu5_frequency: 1328000
    cpu7_frequency: 1745000
```
