### ISSUE TITLE
'sections' usage in agenda

### ISSUE THREAD

**Issue by Leo-Yan** [ARM-software/workload-automation#427]
Hi there,

I tried to use 'sections' in agenda to test multiple kernel images for same test suites, the functionality is partial working, but I saw every test case it will reburn the kernel images, so for example, I have 3 kernel images and have 2 test cases,   Below are the wa agenda file I am using:

```
config:
  instrumentation: [~fps, ~trace-cmd]
  result_processors:
    - json
    - summary_csv

global:
  iterations: 1
  runtime_params:
    sysfile_values:
      /sys/class/devfreq/e82c0000.mali/governor: userspace
      /sys/class/devfreq/e82c0000.mali/userspace/set_freq: 533000000
      /sys/class/thermal/thermal_zone0/sustainable_power: 99999999
      /proc/sys/kernel/sched_use_walt_cpu_util: 0
      /proc/sys/kernel/sched_use_walt_task_util: 0

sections:
  - id: my_kernel_version_1
    flash:
      images:
        boot: /tmp/boot.img

  - id: my_kernel_version_2
    flash:
      images:
        boot: /tmp/boot.img

  - id: my_kernel_version_3
    flash:
      images:
        boot: /tmp/boot.img

workloads:
  - name: idle
    params:
      duration: 5
  - name: audio
    params:
      duration: 10

```

As result I observed the testing flow is as below; we can see there have many times kernel image burning are redundant:

- Burn kernel 1 + test case 1
- Burn kernel 2 + test case 1
- Burn kernel 3 + test case 1
- Burn kernel 1 + test case 2
- Burn kernel 2 + test case 2
- Burn kernel 3 + test case 2

Ideally I expect the testing flow is:

- Burn kernel 1
  test case 1
  test case 2
- Burn kernel 2
  test case 1
  test case 2
- Burn kernel 3
  test case 1
  test case 2

So could give me some suggestion for this case, I want to run the multiple test cases in one going with burning one single kernel image?
