### ISSUE TITLE
Allow workload specific configuration parameters for instruments

### ISSUE THREAD

**Issue by yln** [ARM-software/workload-automation#444]
I am trying to accomplish the following in my agenda:
```yaml
config:
    ....
    instrumentation: [my_instrument]
    my_instrument:
        param1: value1
        param2: value2

workloads:
    - id: wl_1
      ...
      instrumentation:
          my_instrument:
              param3: value3

    - id: wl_2
      ...
      instrumentation:
          my_instrument:
              param2: value4
              param3: value5
```
`my_instrument` has 3 parameters. `param1` and `param2` are set globally. `param3` is set per workload. In `wl_2`, the global value of `param2` is overwritten by a workload-specific one.

Maybe this is already possible? It would greatly simplify my "executable output recorder" instrument, which starts a long-running executable or script and collects its output during workload execution (basically `FilePoller` for commands). I am happy to share this instrument, in case it is deemed useful.

**Comment by setrofim** [comment]
Unfortunately, what you are trying to do is not possible in WA2.  Instruments are configured once on creation at the beginning of the run. From then on, they may be enabled or disabled for a particular iteration, but they cannot be reconfigured. We are looking to change that in the future versions of WA.

**Comment by yln** [comment]
Among the same lines: workload- and section-specific result processors.
```yaml
config:
    ...
    result_processors: [status, csv]

section:
    id: sec_1
    ....
    result_processors: [my_result_processor]   # Additional result processor for section
```
