### ISSUE TITLE
The workload 'youtube_playback' cannot automatically playback stream file 

### ISSUE THREAD

**Issue by Leo-Yan** [ARM-software/workload-automation#815]
Hi there,

When I use workload 'youtube_playback' it cannot automatically playback the stream, I am working on WA 3.0.  Could you give some suggestion for this?

```
workloads:
  - name: youtube_playback
    id: youtube_playback
    workload_params:
       video_url: "http://no-ads-youtube.com/video/rory-finn/partly-cloudy-new-soundtrack?v=HSZZ5Vq3hNw"
       duration: 30

```
