### ISSUE TITLE
No support for YAML anchors?

### ISSUE THREAD

**Issue by PiCT0** [ARM-software/workload-automation#973]
Consider the following YAML agenda:
```YAML
workloads:
-   name: dhrystone
    params: &dhrystone_single_params
        cleanup_assets: true
        cpus: 0
        delay: 3
        duration: 0
        mloops: 10
        threads: 1
-   name: dhrystone
    params:
        <<: *dhrystone_single_params
        threads: 4
```
which uses YAML [anchor nodes](https://en.wikipedia.org/wiki/YAML#Advanced_components) and [alias nodes](https://yaml.org/spec/1.2/spec.html#alias) to express the redundancy between all `dhrystone` parameters used (except from the overloaded `threads`).

When `run`ning this agenda in WA, I receive:
```
ERROR    Error parsing Agenda <name_of_the_agenda>: Syntax Error on line 11: None
```
However, PyYAML [seems to support aliases](https://pyyaml.org/wiki/PyYAMLDocumentation) so, if it's not coming from my setup, this error could point to a misuse of PyYAML by WA(?) I believe PyYAML should make the "duplication" transparent to the calling code so that WA might not even be aware of the use of YAML aliases.

This is using:
  - WA 3.1.3.dev1 (`pip`-installed in development mode);
  - PyYAML 5.1
